# Generated by Django 4.0 on 2024-08-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0002_action_target_ct_action_target_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='actions_act_created_64f10d_idx',
        ),
    ]
