# Generated by Django 4.0 on 2024-08-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_alter_action_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['target_ct', 'target_id'], name='actions_act_target__f20513_idx'),
        ),
    ]
