# Generated by Django 4.0 on 2024-09-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_like'], name='images_imag_total_l_e2ea5d_idx'),
        ),
    ]
