# Generated by Django 4.0 on 2024-09-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_total_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='total_like',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
