# Generated by Django 4.0 on 2024-09-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_total_like'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_total_l_e2ea5d_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='total_like',
        ),
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['-total_likes'], name='images_imag_total_l_0bcd7e_idx'),
        ),
    ]
