# Generated by Django 4.0 on 2024-09-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_images_imag_total_l_e2ea5d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
