# Generated by Django 4.0 on 2024-09-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_total_likes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='images_imag_total_l_0bcd7e_idx',
        ),
        migrations.RemoveField(
            model_name='image',
            name='total_likes',
        ),
    ]
